#!/bin/bash
#disperseGit

#Installer script for git files




####### FIRST BLOCK #######
###########################

#rfb.service
echo "Installing rfb.service to avahi"

#directory to file
cd /etc/avahi/services
sudo touch rfb.service
sleep 1
echo -n "."

#bakup original file
#sudo cp /etc/avahi/services/rfb.service /etc/avahi/services/rfb.service.OLD
#sudo touch /etc/avahi/services/rfb.service.OLD
#cat /etc/avahi/services/rfb.service 2>&1 | sudo tee /etc/avahi/services/rfb.service.OLD
sudo tee /etc/avahi/services/rfb.service.OLD < /etc/avahi/services/rfb.service >/dev/null/
sleep 1
echo -n "."

#transfer in new file
#sudo cp /media/GitRepos/UbuntuMateDev/sysFiles/rfb.service /etc/avahi/services/rfb.service
#cat /media/GitRepos/UbuntuMateDev/sysFiles/rfb.service 2>&1 | sudo tee /etc/avahi/services/rfb.service
sudo tee /etc/avahi/services/rfb.service < /media/GitRepos/UbuntuMateDev/sysFiles/rfb.service
sleep 1
echo ".[ok]"

#########################
########## END ##########


####### NEXT BLOCK #######
##########################

#afpd.service
echo -n "Installing afpd.service to avahi"

#directory to file
cd /etc/avahi/services 
sleep 1
echo -n "."

#bakup original file sudo cp /etc/avahi/services/afpd.service /etc/avahi/services/afpd.service.OLD
sleep 1
echo -n "."

#transfer in new file sudo cp /media/GitRepos/UbuntuMateDev/sysFiles/afpd.service
#/etc/avahi/services/afpd.service
sleep 1
echo ".[ok]"

#########################
########## END ##########


exit 0
